version: 2.1

jobs:
  build:
    docker:
      - image: tuplestream/bumpversion:latest
    steps:
      - checkout
      - run:
          name: Update formula details
          command: |
            git clone https://github.com/tuplestream/tuplectl -b master
            VERSION=$(cat ./tuplectl/VERSION)
            curl -L "https://github.com/tuplestream/tuplectl/releases/download/v$(VERSION)/tuplectl-darwin-amd64.sha256sum" -o checksum
            CHECKSUM=$(cat checksum)
            sed -e "s/    version.*/    version \"$VERSION\"/" Formula/tuplectl.rb > tmpFormula
            sed -E "s/v[0-9]+\.[0-9]+\.[0-9]+/v$VERSION/" tmpFormula > updated
            sed -e "s/      sha256.*/      sha256 \"$CHECKSUM\"/" updated > Formula/tuplectl.rb
            cat Formula/tuplectl.rb
